### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by pmillspaugh** [pmillspaugh/petemillspaugh.com#17]
Potential upgrades to search experience:

- [x] surface `sub_results` from each page
- [x] exclude irrelevant pages, e.g. `/404`
- [x] exclude non-content elements with `data-pagefind-ignore` attribute
- [x] debounce input to avoid results flash
- [x] Add 'Search' to floating trigger to make it more obvious

**Comment by noxify** [comment]
Hi @pmillspaugh,

not sure if this is the right place, but it seems that you can use `pre` and `post` scripts with `pnpm`.

https://pnpm.io/cli/run#enable-pre-post-scripts

**Comment by pmillspaugh** [comment]
Good catch! I'll update my write-up to note that.

**Comment by pmillspaugh** [comment]
Addressed in #19

**Comment by pmillspaugh** [comment]
Addressed in https://github.com/pmillspaugh/petemillspaugh.com/pull/19
